version: "3"

services:
  nuxt:
    build:
      context: .
      dockerfile: DockerfileDev
    tty: true
    command: /bin/sh -c "yarn run dev"
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    ports:
      - 8080:3000

volumes:
  node-modules:
